name: "Pull request to develop"

on:
  pull_request:
    branches: [develop]

jobs:
  development-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Alert on build
        env:
          SLACK_WEBHOOK_SECRET: T06ENM176KH/B06G6ACEK7A/TMdFaSiSu8Cj1aKc6Oe5Bx4A
          SLACK_MESSAGE: ":orc_worker: Pull request is ready to review <${{ github.pull_request.url }}|*PR#{{ github.pull_request.id }}*>"
          SLACK_TEST_MESSAGE: "Github object view ${{ github }}"
        run: |
         chmod +x ./.github/workflows/develop-slack-notify.sh
        shell: bash
