name: "Pull request to develop"

on:
  pull_request:
    branches: [develop]

jobs:
  development-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get full PR link
        id: vars
        run: |
          PR_URL="${{ github.event.pull_request._links.html.href }}"
          PR_NUMBER="${{ github.event.number }}"
          echo PR_NUMBER="$PR_NUMBER" >> "$GITHUB_OUTPUT"
          echo "PR_URL=$PR_URL" >> "$GITHUB_OUTPUT"

      - name: Alert on build
        if: github.event.action == 'opened'
        env:
          SLACK_WEBHOOK_SECRET: ${{ secrets.SLACK_WEBHOOK_SECRET }}
          SLACK_MESSAGE: ":orc_worker: New pull request is ready to review <${{ steps.vars.outputs.PR_URL }}| *PR#${{ steps.vars.outputs.PR_NUMBER }}*>"
        run: ./.github/workflows/develop-slack-notify.sh
        shell: bash
